/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ClienteDAO;
import Model.Cliente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henri
 */
public class ClienteView extends javax.swing.JInternalFrame {
        Cliente cliente;
        ClienteDAO clienteDAO;
        List<Cliente> listaClientes;
        
    public ClienteView() {
        clienteDAO = new ClienteDAO();
        listaClientes = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEnderecoCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBairroCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCidadeCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEstadoCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnNovoCliente = new javax.swing.JButton();
        btnSalvarCliente = new javax.swing.JButton();
        btnAlterarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        txtTelefoneCliente = new javax.swing.JFormattedTextField();
        txtLimiteCreditoCliente = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCepCliente = new javax.swing.JFormattedTextField();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1360, 898));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Código");

        txtIdCliente.setEnabled(false);

        txtNomeCliente.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("CPF");

        txtEmailCliente.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        txtEnderecoCliente.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Endereço");

        txtNumeroCliente.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Número");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Telefone");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Bairro");

        txtBairroCliente.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Cidade");

        txtCidadeCliente.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Estado");

        txtEstadoCliente.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("CEP");

        btnNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btnSalvarCliente.setAlignmentY(0.0F);
        btnSalvarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalvarCliente.setEnabled(false);
        btnSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarClienteActionPerformed(evt);
            }
        });

        btnAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        btnAlterarCliente.setEnabled(false);
        btnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btnExcluirCliente.setEnabled(false);
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setText("Clientes");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Limite de Crédito");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCliente);

        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.setEnabled(false);

        try {
            txtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneCliente.setEnabled(false);

        txtLimiteCreditoCliente.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Novo Cliente");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setLabelFor(btnSalvarCliente);
        jLabel15.setText("Salvar");
        jLabel15.setAlignmentY(0.0F);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Cancelar");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Alterar");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Excluir");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientepainel.png"))); // NOI18N

        try {
            txtCepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCepCliente.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeCliente)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSalvarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)))))
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 422, Short.MAX_VALUE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(btnAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(69, 69, 69)
                                        .addComponent(jLabel18)
                                        .addGap(25, 25, 25))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNumeroCliente)
                                    .addComponent(txtTelefoneCliente)
                                    .addComponent(txtCpfCliente))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
                                    .addComponent(txtEnderecoCliente)
                                    .addComponent(txtBairroCliente)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtCidadeCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(504, 504, 504))
                                    .addComponent(txtCepCliente))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLimiteCreditoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(484, 484, 484)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(142, 142, 142))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLimiteCreditoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCliente)
                    .addComponent(btnSalvarCliente)
                    .addComponent(btnAlterarCliente)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarClienteActionPerformed
          if (txtNomeCliente.getText().isEmpty() || txtCpfCliente.getText().isEmpty() || txtTelefoneCliente.getText().isEmpty()
              || txtEnderecoCliente.getText().isEmpty() || txtNumeroCliente.getText().isEmpty() || txtBairroCliente.getText().isEmpty()
              || txtCidadeCliente.getText().isEmpty() || txtEstadoCliente.getText().isEmpty() || txtCepCliente.getText().isEmpty() || txtLimiteCreditoCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");
            txtNomeCliente.requestFocusInWindow();
        } else{
            cliente = new Cliente();
            cliente.setNomeCliente(txtNomeCliente.getText());
            cliente.setCpfCliente(txtCpfCliente.getText());
            cliente.setEmailCliente(txtEmailCliente.getText());
            cliente.setTelCliente(txtTelefoneCliente.getText());
            cliente.setEnderecoCliente(txtEnderecoCliente.getText());
            cliente.setNumeroCliente(txtNumeroCliente.getText());
            cliente.setBairroCliente(txtBairroCliente.getText());
            cliente.setCidadeCliente(txtCidadeCliente.getText());
            cliente.setEstadoCliente(txtEstadoCliente.getText());
            cliente.setCepCliente(txtCepCliente.getText());
            cliente.setLimite_creditoCliente(Float.valueOf(txtLimiteCreditoCliente.getText()));
             try {
                 clienteDAO.salvar(cliente);
             } catch (SQLException ex) {
                 Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
             }
                    JOptionPane.showMessageDialog(null, "Cliente Salvo com Sucesso!!!"); 
                    atualizarTabelaCliente();
                    preparaSalvareCancelar();
                    desativaCampos();
                    limpaCamposCliente();
         }
    }//GEN-LAST:event_btnSalvarClienteActionPerformed

    private void btnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClienteActionPerformed
        preparaAlterar();
        ativaCampos();
        if (txtIdCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o cliente");
        }else{
            cliente = new Cliente();
            cliente.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            cliente.setNomeCliente(txtNomeCliente.getText());
            cliente.setCpfCliente(txtCpfCliente.getText());
            cliente.setEmailCliente(txtEmailCliente.getText());
            cliente.setTelCliente(txtTelefoneCliente.getText());
            cliente.setEnderecoCliente(txtEnderecoCliente.getText());
            cliente.setNumeroCliente(txtNumeroCliente.getText());
            cliente.setBairroCliente(txtBairroCliente.getText());
            cliente.setCidadeCliente(txtCidadeCliente.getText());
            cliente.setEstadoCliente(txtEstadoCliente.getText());
            cliente.setCepCliente(txtCepCliente.getText());
            cliente.setLimite_creditoCliente(Float.valueOf(txtLimiteCreditoCliente.getText()));
            
            try {
                clienteDAO.alterar(cliente);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
                    JOptionPane.showMessageDialog(null, "Cliente Alterado com Sucesso!!!"); 
                    limpaCamposCliente();
                    atualizarTabelaCliente();
                    preparaSalvareCancelar();
                    desativaCampos();
        }
    }//GEN-LAST:event_btnAlterarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
         if (txtIdCliente.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o cliente");
        }else{
            cliente = new Cliente();
            cliente.setIdCliente(Integer.parseInt(txtIdCliente.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + txtNomeCliente.getText());
            if (confirma == 0){
                try {
                    clienteDAO.excluir(cliente);
                } catch (SQLException ex) {
                    Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
                }
                    JOptionPane.showMessageDialog(null, "Cliente Excluido com Sucesso!!!"); 
                    limpaCamposCliente();
                    atualizarTabelaCliente();
                    preparaExcluir();
            }
         }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        ativaCampos();
        preparaNovo();
        limpaCamposCliente();
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
         txtIdCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 0).toString());
        txtNomeCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 1).toString());
        txtCpfCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 2).toString());
        txtEmailCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 3).toString());
        txtTelefoneCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 4).toString());
        txtEnderecoCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 5).toString());
        txtNumeroCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 6).toString());
        txtBairroCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 7).toString());
        txtCidadeCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 8).toString());
        txtEstadoCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 9).toString());
        txtCepCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 10).toString());
        txtLimiteCreditoCliente.setText(tblCliente.getValueAt(tblCliente.getSelectedRow(), 11).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tblClienteMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposCliente();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed
           
    public void atualizarTabelaCliente(){
        cliente = new Cliente();
            try {
                listaClientes = clienteDAO.ListaCliente();
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
                String dados [][] = new String[listaClientes.size()][12];
                int i = 0;
               for (Cliente cliente : listaClientes){
                    dados[i][0] = String.valueOf(cliente.getIdCliente());
                    dados[i][1] = cliente.getNomeCliente();
                    dados[i][2] = cliente.getCpfCliente();
                    dados[i][3] = cliente.getEmailCliente();
                    dados[i][4] = cliente.getTelCliente();
                    dados[i][5] = cliente.getEnderecoCliente();
                    dados[i][6] = cliente.getNumeroCliente();
                    dados[i][7] = cliente.getBairroCliente();
                    dados[i][8] = cliente.getCidadeCliente();
                    dados[i][9] = cliente.getEstadoCliente();
                    dados[i][10] = cliente.getCepCliente();
                    dados[i][11] = String.valueOf(cliente.getLimite_creditoCliente());
                    i++;
                }
                String tituloColuna[] = {"IdCliente", "Nome", "CPF", "Email", "Telefone", "Endereço", 
                "Número", "Bairro", "Cidade", "Estado", "CEP", "Limite de Crédito"};
                DefaultTableModel tabelaCliente = new DefaultTableModel();
                tabelaCliente.setDataVector(dados, tituloColuna);
                tblCliente.setModel(new DefaultTableModel(dados, tituloColuna){
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false, false, false, false, false, false, false
                    };
                   
                        public boolean isCellEdiTable(int rowIndex, int columnIndex){
                            return canEdit[columnIndex];
                        }
                });
                tblCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(1).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(2).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(4).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(5).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(6).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(7).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(8).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(9).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(10).setPreferredWidth(100);
                tblCliente.getColumnModel().getColumn(11).setPreferredWidth(100);
                
                
                DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
                centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                tblCliente.getColumnModel().getColumn(0).setCellRenderer(centralizado);
                tblCliente.setRowHeight(25);
                tblCliente.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnSalvarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBairroCliente;
    private javax.swing.JFormattedTextField txtCepCliente;
    private javax.swing.JTextField txtCidadeCliente;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtEstadoCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JFormattedTextField txtLimiteCreditoCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNumeroCliente;
    private javax.swing.JFormattedTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables

private void limpaCamposCliente() {
        txtIdCliente.setText("");
        txtNomeCliente.setText("");
        txtCpfCliente.setText("");
        txtEmailCliente.setText("");
        txtTelefoneCliente.setText("");
        txtEnderecoCliente.setText("");
        txtNumeroCliente.setText("");
        txtBairroCliente.setText("");
        txtCidadeCliente.setText("");
        txtEstadoCliente.setText("");
        txtCepCliente.setText("");
        txtLimiteCreditoCliente.setText("");
    }

public void ativaCampos(){
	txtNomeCliente.setEnabled(true);
	txtCpfCliente.setEnabled(true);
	txtEmailCliente.setEnabled(true);
	txtTelefoneCliente.setEnabled(true);
	txtEnderecoCliente.setEnabled(true);
	txtNumeroCliente.setEnabled(true);
	txtBairroCliente.setEnabled(true);
	txtCidadeCliente.setEnabled(true);
	txtEstadoCliente.setEnabled(true);
	txtCepCliente.setEnabled(true);
	txtLimiteCreditoCliente.setEnabled(true);
}

public void desativaCampos(){
	txtNomeCliente.setEnabled(false);
	txtCpfCliente.setEnabled(false);
	txtEmailCliente.setEnabled(false);
	txtTelefoneCliente.setEnabled(false);
	txtEnderecoCliente.setEnabled(false);
	txtNumeroCliente.setEnabled(false);
	txtBairroCliente.setEnabled(false);
	txtCidadeCliente.setEnabled(false);
	txtEstadoCliente.setEnabled(false);
	txtCepCliente.setEnabled(false);
	txtLimiteCreditoCliente.setEnabled(false);
}

public void preparaNovo(){
    btnNovoCliente.setEnabled(false);
    btnSalvarCliente.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarCliente.setEnabled(false);
    btnExcluirCliente.setEnabled(false);
    tblCliente.setEnabled(false);
    tblCliente.clearSelection();
}

public void preparaSalvareCancelar(){
    btnNovoCliente.setEnabled(true);
    btnSalvarCliente.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnAlterarCliente.setEnabled(false);
    btnExcluirCliente.setEnabled(false);
    tblCliente.setEnabled(true);
    tblCliente.clearSelection();
}

public void preparaSelecaoTabela(){
    btnNovoCliente.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarCliente.setEnabled(true);
    btnExcluirCliente.setEnabled(true); 
    ativaCampos();
}

public void preparaAlterar(){
    btnNovoCliente.setEnabled(false);
    btnSalvarCliente.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarCliente.setEnabled(false);
    btnExcluirCliente.setEnabled(false);   
    tblCliente.setEnabled(false);
    tblCliente.clearSelection();
}

public void preparaExcluir(){
    btnExcluirCliente.setEnabled(false);
    btnAlterarCliente.setEnabled(false);
}

}
