/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import Model.Cliente;
import Model.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bittenks_win
 */
public class ProdutoView extends javax.swing.JInternalFrame {

        Produto produto;
        ProdutoDAO produtoDAO;
        List<Produto> listaProdutos;

    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        produtoDAO = new ProdutoDAO();
        listaProdutos = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExcluirProduto = new javax.swing.JButton();
        btnNovoProduto = new javax.swing.JButton();
        txtdescricaoProduto = new javax.swing.JTextField();
        txtIdProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSalvarProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtvalorProduto = new javax.swing.JTextField();
        txtquantidadeProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcategoriaProduto = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAlterarProduto1 = new javax.swing.JButton();
        txtmarcaProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Código");

        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnNovoProduto.setText("Novo");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("Produtos");

        btnSalvarProduto.setText("Salvar");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição");

        jLabel13.setText("Valor");

        jLabel9.setText("Quantidade");

        jLabel10.setText("Categoria");

        jLabel11.setText("Marca");

        btnAlterarProduto1.setText("Alterar");
        btnAlterarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProduto1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        btnBuscarProd.setText("Buscar");
        btnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdActionPerformed(evt);
            }
        });

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdescricaoProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnNovoProduto)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvarProduto)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarProd)))
                                .addGap(0, 34, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAlterarProduto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirProduto)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(txtmarcaProduto)
                                    .addComponent(txtquantidadeProduto)
                                    .addComponent(txtcategoriaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jLabel13))
                                .addGap(252, 252, 252))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtvalorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(204, 204, 204)
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtquantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(txtmarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(8, 8, 8)
                        .addComponent(txtcategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvalorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoProduto)
                    .addComponent(btnSalvarProduto)
                    .addComponent(btnAlterarProduto1)
                    .addComponent(btnExcluirProduto)
                    .addComponent(btnBuscarProd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (txtIdProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o produto");
        }else{
            produto = new Produto();
            produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + txtNomeProduto.getText());
            if (confirma == 0){
                try {
                    produtoDAO.excluir(produto);
                } catch (SQLException ex) {
                    Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                //limpaCamposProduto();
                JOptionPane.showMessageDialog(null, "Produto Excluido com Sucesso!!!");
            }
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        //limpaCamposProduto();
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        if (txtNomeProduto.getText().isEmpty() || txtdescricaoProduto.getText().isEmpty()
            || txtquantidadeProduto.getText().isEmpty() || txtcategoriaProduto.getText().isEmpty() || txtmarcaProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");
            txtNomeProduto.requestFocusInWindow();
        } else{
            produto = new Produto();
            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setDescricaoProduto(txtdescricaoProduto.getText());
            produto.setQuantidadeProduto(Integer.parseInt(txtquantidadeProduto.getText()));
            produto.setValorProduto(Float.valueOf(txtvalorProduto.getText()));;
            produto.setCategoriaProduto(txtcategoriaProduto.getText());
            produto.setMarcaProduto(txtmarcaProduto.getText());
            

            try {
                produtoDAO.salvar(produto);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            //limpaCamposProduto();
            atualizarTabelaProduto();
            JOptionPane.showMessageDialog(null, "Produto Salvo com Sucesso!!!");
        }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void btnAlterarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProduto1ActionPerformed
    if (txtIdProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o produto");
        }else{
            produto = new Produto();
            produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));
            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setDescricaoProduto(txtdescricaoProduto.getText());
            produto.setQuantidadeProduto(Integer.parseInt(txtIdProduto.getText()));
            produto.setCategoriaProduto(txtcategoriaProduto.getText());
            produto.setMarcaProduto(txtmarcaProduto.getText());
            produto.setValorProduto(Integer.parseInt(txtIdProduto.getText()));;

            try {
                produtoDAO.alterar(produto);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            //limpaCamposProduto();
            JOptionPane.showMessageDialog(null, "Produto Alterado com Sucesso!!!");
        }
    }//GEN-LAST:event_btnAlterarProduto1ActionPerformed

    private void btnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdActionPerformed
        String cod = JOptionPane.showInputDialog("Digite o Código do Produto");
        produto = new Produto();
            try {
                produto = produtoDAO.buscaProdutoCodigo(cod);
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtNomeProduto.setText(produto.getNomeProduto());
            txtdescricaoProduto.setText(produto.getDescricaoProduto());
            txtquantidadeProduto.setText(String.valueOf(produto.getQuantidadeProduto()));
            txtvalorProduto.setText(String.valueOf(produto.getValorProduto()));
            txtcategoriaProduto.setText(produto.getCategoriaProduto());
            txtmarcaProduto.setText(produto.getMarcaProduto());
    }//GEN-LAST:event_btnBuscarProdActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        txtIdProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString());
        txtdescricaoProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
        txtdescricaoProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
        txtvalorProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3).toString());
        txtcategoriaProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4).toString());
        txtmarcaProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tblProdutoMouseClicked

    public void atualizarTabelaProduto(){
        produto = new Produto();
            try {
                listaProdutos = produtoDAO.ListaProduto();
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
                String dados [][] = new String[listaProdutos.size()][7];
                int i = 0;
               for (Produto produto : listaProdutos){
                    dados[i][0] = String.valueOf(produto.getIdProduto());
                    dados[i][1] = produto.getNomeProduto();
                    dados[i][2] = produto.getDescricaoProduto();
                    dados[i][3] = String.valueOf(produto.getQuantidadeProduto());
                    dados[i][4] = String.valueOf(produto.getValorProduto());
                    dados[i][5] = produto.getCategoriaProduto();
                    dados[i][6] = produto.getMarcaProduto();
                    i++;
                }
                String tituloColuna[] = {"IdProduto", "Nome", "Descrição", "Quantidade", "Valor", "categoria", "Marca"};
                DefaultTableModel tabelaProduto = new DefaultTableModel();
                tabelaProduto.setDataVector(dados, tituloColuna);
                tblProduto.setModel(new DefaultTableModel(dados, tituloColuna){
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false, false
                    };
                   
                        public boolean isCellEdiTable(int rowIndex, int columnIndex){
                            return canEdit[columnIndex];
                        }
                });
                tblProduto.getColumnModel().getColumn(0).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(5).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(6).setPreferredWidth(100);

                
                
                DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
                centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                tblProduto.getColumnModel().getColumn(0).setCellRenderer(centralizado);
                tblProduto.setRowHeight(25);
                tblProduto.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProduto1;
    private javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtcategoriaProduto;
    private javax.swing.JTextField txtdescricaoProduto;
    private javax.swing.JTextField txtmarcaProduto;
    private javax.swing.JTextField txtquantidadeProduto;
    private javax.swing.JTextField txtvalorProduto;
    // End of variables declaration//GEN-END:variables
}
