/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.FuncionarioDAO;
import Model.Funcionario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henri
 */
public class FuncionarioView extends javax.swing.JInternalFrame {

        Funcionario funcionario;
        FuncionarioDAO funcionarioDAO;
        List<Funcionario> listaFuncionarios;
    /**
     * Creates new form FuncionarioView
     */
    public FuncionarioView() {
        funcionarioDAO = new FuncionarioDAO();
        listaFuncionarios = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal4 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        txtCodigoUsuario4 = new javax.swing.JTextField();
        txtNomeUsuario4 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        txtCpfUsuario4 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        txtEnderecoUsuario4 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtTelefoneUsuario4 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtEmailUsuario4 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        Senha4 = new javax.swing.JLabel();
        txtFuncaoUsuario4 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        btnNovo4 = new javax.swing.JButton();
        btnExcluir4 = new javax.swing.JButton();
        btnSalvar4 = new javax.swing.JButton();
        btnAlterar4 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblFuncionario4 = new javax.swing.JTable();
        btnCancelar4 = new javax.swing.JButton();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtSenhaUsuario4 = new javax.swing.JPasswordField();
        jLabel70 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1360, 898));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel57.setText("Código");

        txtCodigoUsuario4.setEnabled(false);

        txtNomeUsuario4.setEnabled(false);

        jLabel58.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel58.setText("Nome");

        txtCpfUsuario4.setEnabled(false);

        jLabel59.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel59.setText("CPF");

        txtEnderecoUsuario4.setEnabled(false);

        jLabel60.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel60.setText("Endereço");

        txtTelefoneUsuario4.setEnabled(false);

        jLabel61.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel61.setText("Telefone");

        txtEmailUsuario4.setEnabled(false);

        jLabel62.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel62.setText("Email");

        Senha4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Senha4.setText("Senha");

        txtFuncaoUsuario4.setEnabled(false);

        jLabel63.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel63.setText("Função");

        btnNovo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        btnNovo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btnExcluir4.setEnabled(false);
        btnExcluir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btnSalvar4.setEnabled(false);
        btnSalvar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        btnAlterar4.setEnabled(false);
        btnAlterar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel64.setText("Funcionários");

        tblFuncionario4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblFuncionario4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblFuncionario4);

        btnCancelar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar4.setEnabled(false);
        btnCancelar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel65.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel65.setText("Novo Funcionário");

        jLabel66.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel66.setText("Salvar");

        jLabel67.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel67.setText("Cancelar");

        jLabel68.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel68.setText("Alterar");

        jLabel69.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel69.setText("Excluir");

        txtSenhaUsuario4.setEnabled(false);

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionarios.png"))); // NOI18N

        javax.swing.GroupLayout pnlPrincipal4Layout = new javax.swing.GroupLayout(pnlPrincipal4);
        pnlPrincipal4.setLayout(pnlPrincipal4Layout);
        pnlPrincipal4Layout.setHorizontalGroup(
            pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                        .addComponent(txtNomeUsuario4)
                        .addContainerGap())
                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                        .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel64)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel70)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipal4Layout.createSequentialGroup()
                        .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipal4Layout.createSequentialGroup()
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCpfUsuario4, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                        .addComponent(txtTelefoneUsuario4))
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel58)
                                    .addComponent(jLabel61))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailUsuario4)
                                    .addComponent(txtEnderecoUsuario4)
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel62)
                                            .addComponent(jLabel60))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipal4Layout.createSequentialGroup()
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addComponent(btnNovo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvar4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addComponent(jLabel65)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel66)
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel67)))
                                .addGap(727, 727, 727)
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlterar4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel68)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnExcluir4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipal4Layout.createSequentialGroup()
                                        .addComponent(jLabel69)
                                        .addGap(28, 28, 28))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipal4Layout.createSequentialGroup()
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSenhaUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Senha4))
                                .addGap(18, 18, 18)
                                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                                        .addComponent(jLabel63)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtFuncaoUsuario4))))
                        .addContainerGap())))
        );
        pnlPrincipal4Layout.setVerticalGroup(
            pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel64))
                    .addGroup(pnlPrincipal4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel70)))
                .addGap(44, 44, 44)
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(jLabel60))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnderecoUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(jLabel62))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Senha4)
                    .addComponent(jLabel63))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFuncaoUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterar4)
                    .addComponent(btnSalvar4)
                    .addComponent(btnCancelar4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNovo4)
                        .addComponent(btnExcluir4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipal4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(jLabel66)
                    .addComponent(jLabel67)
                    .addComponent(jLabel68)
                    .addComponent(jLabel69))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposFuncionario();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        txtCodigoUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 0).toString());
        txtNomeUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 1).toString());
        txtCpfUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 2).toString());
        txtEnderecoUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 3).toString());
        txtTelefoneUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 4).toString());
        txtEmailUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 5).toString());
        txtSenhaUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 6).toString());
        txtFuncaoUsuario4.setText(tblFuncionario4.getValueAt(tblFuncionario4.getSelectedRow(), 7).toString());
        preparaSelecaoTabela();
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        preparaAlterar();
        ativaCampos();
        if (txtCodigoUsuario4.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o Funcionário");
        }else{
            funcionario = new Funcionario();
            funcionario.setIdUsuario(Integer.parseInt(txtCodigoUsuario4.getText()));
            funcionario.setNomeUsuario(txtNomeUsuario4.getText());
            funcionario.setCpfUsuario(txtCpfUsuario4.getText());
            funcionario.setEnderecoUsuario(txtEnderecoUsuario4.getText());
            funcionario.setTelUsuario(txtTelefoneUsuario4.getText());
            funcionario.setEmailUsuario(txtEmailUsuario4.getText());
            funcionario.setSenhaUsuario(txtSenhaUsuario4.getText());
            funcionario.setFuncaoUsuario(txtFuncaoUsuario4.getText());
            try {
                funcionarioDAO.alterar(funcionario);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Funcionário Alterado com Sucesso!!!");
            limpaCamposFuncionario();
            atualizarTabelaFuncionario();
            preparaSalvareCancelar();
            desativaCampos();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNomeUsuario4.getText().isEmpty() || txtCpfUsuario4.getText().isEmpty() || txtEnderecoUsuario4.getText().isEmpty()
            || txtTelefoneUsuario4.getText().isEmpty() || txtEmailUsuario4.getText().isEmpty() || txtSenhaUsuario4.getText().isEmpty()
            || txtFuncaoUsuario4.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");
            txtNomeUsuario4.requestFocusInWindow();
        } else{
            funcionario = new Funcionario();
            funcionario.setNomeUsuario(txtNomeUsuario4.getText());
            funcionario.setCpfUsuario(txtCpfUsuario4.getText());
            funcionario.setEnderecoUsuario(txtEnderecoUsuario4.getText());
            funcionario.setTelUsuario(txtTelefoneUsuario4.getText());
            funcionario.setEmailUsuario(txtEmailUsuario4.getText());
            funcionario.setSenhaUsuario(txtSenhaUsuario4.getText());
            funcionario.setFuncaoUsuario(txtFuncaoUsuario4.getText());
            try {
                funcionarioDAO.salvar(funcionario);
            } catch (SQLException ex) {
                Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Funcionário Salvo com Sucesso!!!");
            atualizarTabelaFuncionario();
            preparaSalvareCancelar();
            desativaCampos();
            limpaCamposFuncionario();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtCodigoUsuario4.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o Funcionário");
        }else{
            funcionario = new Funcionario();
            funcionario.setIdUsuario(Integer.parseInt(txtCodigoUsuario4.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + txtNomeUsuario4.getText());
            if (confirma == 0){
                try {
                    funcionarioDAO.excluir(funcionario);
                } catch (SQLException ex) {
                    Logger.getLogger(FuncionarioView.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Funcionário Excluido com Sucesso!!!");
                limpaCamposFuncionario();
                atualizarTabelaFuncionario();
                preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        ativaCampos();
        preparaNovo();
        limpaCamposFuncionario();
    }//GEN-LAST:event_btnNovoActionPerformed

    public void atualizarTabelaFuncionario(){
        funcionario = new Funcionario();
            try {
                listaFuncionarios = funcionarioDAO.ListaFuncionario();
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
                String dados [][] = new String[listaFuncionarios.size()][8];
                int i = 0;
               for (Funcionario funcionario : listaFuncionarios){
                    dados[i][0] = String.valueOf(funcionario.getIdUsuario());
                    dados[i][1] = funcionario.getNomeUsuario();
                    dados[i][2] = funcionario.getCpfUsuario();
                    dados[i][3] = funcionario.getEnderecoUsuario();
                    dados[i][4] = funcionario.getTelUsuario();
                    dados[i][5] = funcionario.getEmailUsuario();
                    dados[i][6] = funcionario.getSenhaUsuario();
                    dados[i][7] = funcionario.getFuncaoUsuario();
                    i++;
                }
                String tituloColuna[] = {"IdFuncionario", "Nome", "CPF", "Endereço", "Telefone", "Email", 
                "Senha", "Função"};
                DefaultTableModel tabelaFuncionario = new DefaultTableModel();
                tabelaFuncionario.setDataVector(dados, tituloColuna);
                tblFuncionario4.setModel(new DefaultTableModel(dados, tituloColuna){
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false, false, false
                    };
                   
                        public boolean isCellEdiTable(int rowIndex, int columnIndex){
                            return canEdit[columnIndex];
                        }
                });
                tblFuncionario4.getColumnModel().getColumn(0).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(1).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(2).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(3).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(4).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(5).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(6).setPreferredWidth(100);
                tblFuncionario4.getColumnModel().getColumn(7).setPreferredWidth(100);

                
                
                DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
                centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                tblFuncionario4.getColumnModel().getColumn(0).setCellRenderer(centralizado);
                tblFuncionario4.setRowHeight(25);
                tblFuncionario4.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Senha4;
    private javax.swing.JButton btnAlterar4;
    private javax.swing.JButton btnCancelar4;
    private javax.swing.JButton btnExcluir4;
    private javax.swing.JButton btnNovo4;
    private javax.swing.JButton btnSalvar4;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlPrincipal4;
    private javax.swing.JTable tblFuncionario4;
    private javax.swing.JTextField txtCodigoUsuario4;
    private javax.swing.JTextField txtCpfUsuario4;
    private javax.swing.JTextField txtEmailUsuario4;
    private javax.swing.JTextField txtEnderecoUsuario4;
    private javax.swing.JTextField txtFuncaoUsuario4;
    private javax.swing.JTextField txtNomeUsuario4;
    private javax.swing.JPasswordField txtSenhaUsuario4;
    private javax.swing.JTextField txtTelefoneUsuario4;
    // End of variables declaration//GEN-END:variables

    private void limpaCamposFuncionario() {
        txtCodigoUsuario4.setText("");
        txtNomeUsuario4.setText("");
        txtCpfUsuario4.setText("");
        txtEnderecoUsuario4.setText("");
        txtTelefoneUsuario4.setText("");
        txtEmailUsuario4.setText("");
        txtSenhaUsuario4.setText("");
        txtFuncaoUsuario4.setText("");
    }
    
    public void ativaCampos(){
	txtNomeUsuario4.setEnabled(true);
	txtCpfUsuario4.setEnabled(true);
	txtEnderecoUsuario4.setEnabled(true);
	txtTelefoneUsuario4.setEnabled(true);
	txtEmailUsuario4.setEnabled(true);
	txtSenhaUsuario4.setEnabled(true);
	txtFuncaoUsuario4.setEnabled(true);
}
    
    public void desativaCampos(){
	txtNomeUsuario4.setEnabled(false);
	txtCpfUsuario4.setEnabled(false);
	txtEnderecoUsuario4.setEnabled(false);
	txtTelefoneUsuario4.setEnabled(false);
	txtEmailUsuario4.setEnabled(false);
	txtSenhaUsuario4.setEnabled(false);
	txtFuncaoUsuario4.setEnabled(false);
}
    
    public void preparaNovo(){
    btnNovo4.setEnabled(false);
    btnSalvar4.setEnabled(true);
    btnCancelar4.setEnabled(true);
    btnAlterar4.setEnabled(false);
    btnExcluir4.setEnabled(false);
    tblFuncionario4.setEnabled(false);
    tblFuncionario4.clearSelection();
}
    
    public void preparaSalvareCancelar(){
    btnNovo4.setEnabled(true);
    btnSalvar4.setEnabled(false);
    btnCancelar4.setEnabled(false);
    btnAlterar4.setEnabled(false);
    btnExcluir4.setEnabled(false);
    tblFuncionario4.setEnabled(true);
    tblFuncionario4.clearSelection();
}
    
    public void preparaSelecaoTabela(){
    btnNovo4.setEnabled(true);
    btnCancelar4.setEnabled(true);
    btnAlterar4.setEnabled(true);
    btnExcluir4.setEnabled(true); 
    ativaCampos();
}
    
    public void preparaAlterar(){
    btnNovo4.setEnabled(false);
    btnSalvar4.setEnabled(true);
    btnCancelar4.setEnabled(true);
    btnAlterar4.setEnabled(false);
    btnExcluir4.setEnabled(false);   
    tblFuncionario4.setEnabled(false);
    tblFuncionario4.clearSelection();
}
    
    public void preparaExcluir(){
    btnExcluir4.setEnabled(false);
    btnAlterar4.setEnabled(false);
}
    
}
