/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import DAO.CategoriaDAO;
import DAO.ClienteDAO;
import DAO.MarcaDAO;
import DAO.ProdutoDAO;
import Model.Categoria;
import Model.Cliente;
import Model.Marca;
import Model.Produto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author bittenks_win
 */
public class ProdutoView extends javax.swing.JInternalFrame {

        Produto produto;
        ProdutoDAO produtoDAO;
        List<Produto> listaProdutos;
        CategoriaDAO categoriaDAO;
        List<Categoria> listaCategoria;
        MarcaDAO marcaDAO;
        List<Marca> listaMarca;

    /**
     * Creates new form ProdutoView
     */
    public ProdutoView() {
        produtoDAO = new ProdutoDAO();
        listaProdutos = new ArrayList<>();
        categoriaDAO = new CategoriaDAO();
        listaCategoria = new ArrayList<>();
        marcaDAO = new MarcaDAO();
        listaMarca = new ArrayList<>();
        initComponents();
        this.setVisible(true);
        atualizarTabelaProduto();
        preencherComboCategoria();
        preencherComboMarca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnExcluirProduto = new javax.swing.JButton();
        btnNovoProduto = new javax.swing.JButton();
        txtdescricaoProduto = new javax.swing.JTextField();
        txtIdProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnSalvarProduto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtvalorProduto = new javax.swing.JTextField();
        txtquantidadeProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAlterarProduto1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox();
        cbxMarca = new javax.swing.JComboBox();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Código");

        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excluir.png"))); // NOI18N
        btnExcluirProduto.setEnabled(false);
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/novo.png"))); // NOI18N
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        txtdescricaoProduto.setEnabled(false);

        txtIdProduto.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setText("Produtos");

        btnSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        btnSalvarProduto.setEnabled(false);
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descrição");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Valor");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade");

        txtvalorProduto.setEnabled(false);

        txtquantidadeProduto.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Categoria");

        txtNomeProduto.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Marca");

        btnAlterarProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        btnAlterarProduto1.setEnabled(false);
        btnAlterarProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarProduto1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Novo Produto");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Salvar");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Cancelar");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Alterar");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Excluir");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produtos.png"))); // NOI18N

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Categoria" }));
        cbxCategoria.setToolTipText("");
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        cbxMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marca" }));
        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 475, Short.MAX_VALUE))
                            .addComponent(txtdescricaoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13)
                                        .addComponent(txtvalorProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                                        .addComponent(txtquantidadeProduto)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11)
                                        .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(277, 277, 277))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1096, 1096, 1096)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAlterarProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(29, 29, 29))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel5)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel6)))
                                .addGap(978, 978, 978)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtquantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvalorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(8, 8, 8)
                        .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvarProduto)
                            .addComponent(btnNovoProduto)
                            .addComponent(btnCancelar)
                            .addComponent(btnAlterarProduto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)))
                    .addComponent(btnExcluirProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (txtIdProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o produto");
        }else{
            produto = new Produto();
            produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja excluir: " + txtNomeProduto.getText());
            if (confirma == 0){
                try {
                    produtoDAO.excluir(produto);
                } catch (SQLException ex) {
                    Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Produto Excluido com Sucesso!!!");
                    limpaCamposProduto();
                    atualizarTabelaProduto();
                    preparaExcluir();
            }
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        ativaCampos();
        preparaNovo();
        limpaCamposProduto();
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        if (txtNomeProduto.getText().isEmpty() || txtdescricaoProduto.getText().isEmpty()
            || txtquantidadeProduto.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!!!");
            txtNomeProduto.requestFocusInWindow();
        } else{
            produto = new Produto();
            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setDescricaoProduto(txtdescricaoProduto.getText());
            produto.setQuantidadeProduto(Integer.parseInt(txtquantidadeProduto.getText()));
            produto.setValorProduto(Float.valueOf(txtvalorProduto.getText()));;
            produto.setCategoriaProduto(listaCategoria.get(cbxCategoria.getSelectedIndex()));
            produto.setMarcaProduto(listaMarca.get(cbxMarca.getSelectedIndex()));
            

            try {
                produtoDAO.salvar(produto);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Produto Salvo com Sucesso!!!");
                    atualizarTabelaProduto();
                    preparaSalvareCancelar();
                    desativaCampos();
                    limpaCamposProduto();
        
        }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void btnAlterarProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarProduto1ActionPerformed
    preparaAlterar();
        ativaCampos();
        if (txtIdProduto.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Selecione o produto");
        }else{
            produto = new Produto();
            produto.setIdProduto(Integer.parseInt(txtIdProduto.getText()));
            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setDescricaoProduto(txtdescricaoProduto.getText());
            produto.setQuantidadeProduto(Integer.parseInt(txtIdProduto.getText()));
            produto.setCategoriaProduto(listaCategoria.get(cbxCategoria.getSelectedIndex()));
            produto.setMarcaProduto(listaMarca.get(cbxMarca.getSelectedIndex()));
            produto.setValorProduto(Integer.parseInt(txtIdProduto.getText()));;

            try {
                produtoDAO.alterar(produto);
            } catch (SQLException ex) {
                Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Produto Alterado com Sucesso!!!");
                    limpaCamposProduto();
                    atualizarTabelaProduto();
                    preparaSalvareCancelar();
                    desativaCampos();
        }
    }//GEN-LAST:event_btnAlterarProduto1ActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        /*txtIdProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 0).toString());
        txtdescricaoProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
        txtdescricaoProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
        txtvalorProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3).toString());
        cbxCategoria.setSelectedIndex(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4).toString());
        txtmarcaProduto.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 6).toString());
        preparaSelecaoTabela();*/
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpaCamposProduto();
        preparaSalvareCancelar();
        desativaCampos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMarcaActionPerformed

    public void atualizarTabelaProduto(){
        produto = new Produto();
            try {
                listaProdutos = produtoDAO.ListaProduto();
            } catch (SQLException ex) {
                Logger.getLogger(ClienteView.class.getName()).log(Level.SEVERE, null, ex);
            }
                String dados [][] = new String[listaProdutos.size()][6];
                int i = 0;
               for (Produto produto : listaProdutos){
                    dados[i][0] = String.valueOf(produto.getIdProduto());
                    dados[i][1] = produto.getNomeProduto();
                    dados[i][2] = produto.getDescricaoProduto();
                    dados[i][3] = String.valueOf(produto.getQuantidadeProduto());
                    dados[i][4] = String.valueOf(produto.getValorProduto());
                    dados[i][5] = produto.getCategoriaProduto().getDescricaoCatProd();
                    /*dados[i][6] = produto.getMarcaProduto();*/
                    i++;
                }
                String tituloColuna[] = {"IdProduto", "Nome", "Descrição", "Quantidade", "Valor", "categoria"};/*colocar marcar*/
                DefaultTableModel tabelaProduto = new DefaultTableModel();
                tabelaProduto.setDataVector(dados, tituloColuna);
                tblProduto.setModel(new DefaultTableModel(dados, tituloColuna){
                    boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false/*, false*/
                    };
                   
                        public boolean isCellEdiTable(int rowIndex, int columnIndex){
                            return canEdit[columnIndex];
                        }
                });
                tblProduto.getColumnModel().getColumn(0).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(1).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(2).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(3).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
                tblProduto.getColumnModel().getColumn(5).setPreferredWidth(100);
                //tblProduto.getColumnModel().getColumn(6).setPreferredWidth(100);

                
                
                DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
                centralizado.setHorizontalAlignment(SwingConstants.CENTER);
                tblProduto.getColumnModel().getColumn(0).setCellRenderer(centralizado);
                tblProduto.setRowHeight(25);
                tblProduto.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarProduto1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JComboBox cbxCategoria;
    private javax.swing.JComboBox cbxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtdescricaoProduto;
    private javax.swing.JTextField txtquantidadeProduto;
    private javax.swing.JTextField txtvalorProduto;
    // End of variables declaration//GEN-END:variables

    private void limpaCamposProduto() {
        txtIdProduto.setText("");
        txtNomeProduto.setText("");
        txtquantidadeProduto.setText("");
        txtdescricaoProduto.setText("");
        cbxMarca.setSelectedItem("");
        cbxCategoria.setSelectedItem("");
        txtvalorProduto.setText("");
    }
    
    public void ativaCampos(){
	txtNomeProduto.setEnabled(true);
	txtquantidadeProduto.setEnabled(true);
	txtdescricaoProduto.setEnabled(true);
        txtvalorProduto.setEnabled(true);
	cbxMarca.setEnabled(true);
	cbxCategoria.setEnabled(true);
}
    
    public void desativaCampos(){
	txtNomeProduto.setEnabled(false);
	txtquantidadeProduto.setEnabled(false);
	txtdescricaoProduto.setEnabled(false);
	cbxMarca.setEnabled(false);
	cbxCategoria.setEnabled(false);
	txtvalorProduto.setEnabled(false);
}
     
    public void preparaNovo(){
    btnNovoProduto.setEnabled(false);
    btnSalvarProduto.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarProduto1.setEnabled(false);
    btnExcluirProduto.setEnabled(false);
    tblProduto.setEnabled(false);
    tblProduto.clearSelection();
}
    
    public void preparaSalvareCancelar(){
    btnNovoProduto.setEnabled(true);
    btnSalvarProduto.setEnabled(false);
    btnCancelar.setEnabled(false);
    btnAlterarProduto1.setEnabled(false);
    btnExcluirProduto.setEnabled(false);
    tblProduto.setEnabled(true);
    tblProduto.clearSelection();
}
    
    public void preparaSelecaoTabela(){
    btnNovoProduto.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarProduto1.setEnabled(true);
    btnExcluirProduto.setEnabled(true); 
    ativaCampos();
}
    
    public void preparaAlterar(){
    btnNovoProduto.setEnabled(false);
    btnSalvarProduto.setEnabled(true);
    btnCancelar.setEnabled(true);
    btnAlterarProduto1.setEnabled(false);
    btnExcluirProduto.setEnabled(false);   
    tblProduto.setEnabled(false);
    tblProduto.clearSelection();
}
    
    public void preparaExcluir(){
    btnExcluirProduto.setEnabled(false);
    btnAlterarProduto1.setEnabled(false);
}
    public void preencherComboCategoria(){
        try {
            listaCategoria = categoriaDAO.ListaCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Categoria categoria: listaCategoria){
            cbxCategoria.addItem(categoria.getDescricaoCatProd());
        }
    }
    public void preencherComboMarca(){
        try {
            listaMarca = marcaDAO.ListaMarca();
        } catch (SQLException ex) {
            Logger.getLogger(ProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Marca marca: listaMarca){
            cbxMarca.addItem(marca.getDescricao());
        }
    }
}
