/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Funcionario;
import javax.swing.JFrame;

/**
 *
 * @author henri
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal(Funcionario funcionario) {
        initComponents();
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        if(funcionario.getFuncaoUsuario().equals("vendedor")){
            jmiCadastrarProdutos.setVisible(false);
            jmiCadastrarFuncionarios.setVisible(false);
            jmiCadastrarCategoria.setVisible(false);
            jmiCadastrarMarca.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiNovaVenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiCadastrarCliente = new javax.swing.JMenuItem();
        jmiCadastrarProdutos = new javax.swing.JMenuItem();
        jmiCadastrarFuncionarios = new javax.swing.JMenuItem();
        jmiCadastrarCategoria = new javax.swing.JMenuItem();
        jmiCadastrarMarca = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tela-inicial.png"))); // NOI18N

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trade24.png"))); // NOI18N
        jMenu2.setText("Vendas");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jmiNovaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shopping cart.png"))); // NOI18N
        jmiNovaVenda.setText("Nova Venda");
        jmiNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNovaVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNovaVenda);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add 24.png"))); // NOI18N
        jMenu4.setText("Cadastros");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jmiCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jmiCadastrarCliente.setText("Cadastrar Cliente");
        jmiCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCadastrarCliente);

        jmiCadastrarProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product.png"))); // NOI18N
        jmiCadastrarProdutos.setText("Cadastrar Produtos");
        jmiCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCadastrarProdutos);

        jmiCadastrarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/worker.png"))); // NOI18N
        jmiCadastrarFuncionarios.setText("Cadastrar Funcionários");
        jmiCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarFuncionariosActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCadastrarFuncionarios);

        jmiCadastrarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jmiCadastrarCategoria.setText("Cadastrar Categoria");
        jmiCadastrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarCategoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCadastrarCategoria);

        jmiCadastrarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Marca.png"))); // NOI18N
        jmiCadastrarMarca.setText("Cadastrar Marca");
        jmiCadastrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarMarcaActionPerformed(evt);
            }
        });
        jMenu4.add(jmiCadastrarMarca);

        jMenuBar1.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saida.png"))); // NOI18N
        jMenu3.setText("Sair");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saida.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNovaVendaActionPerformed
        VendasView venda = new VendasView();
        pnlPrincipal.removeAll();
        pnlPrincipal.add(venda);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiNovaVendaActionPerformed

    private void jmiCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarClienteActionPerformed
        ClienteView cliente = new ClienteView();
        pnlPrincipal.removeAll();
        pnlPrincipal.add(cliente);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiCadastrarClienteActionPerformed

    private void jmiCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarProdutosActionPerformed
        ProdutoView produto = new ProdutoView();
         pnlPrincipal.removeAll();
        pnlPrincipal.add(produto);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiCadastrarProdutosActionPerformed

    private void jmiCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarFuncionariosActionPerformed
         FuncionarioView funcionario = new FuncionarioView();
          pnlPrincipal.removeAll();
        pnlPrincipal.add(funcionario);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiCadastrarFuncionariosActionPerformed

    private void jmiCadastrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarCategoriaActionPerformed
        CategoriaView categoria = new CategoriaView();
        pnlPrincipal.removeAll();
        pnlPrincipal.add(categoria);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiCadastrarCategoriaActionPerformed

    private void jmiCadastrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarMarcaActionPerformed
        MarcaView marca = new MarcaView();
        pnlPrincipal.removeAll();
        pnlPrincipal.add(marca);
        pnlPrincipal.updateUI();
    }//GEN-LAST:event_jmiCadastrarMarcaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmiCadastrarCategoria;
    private javax.swing.JMenuItem jmiCadastrarCliente;
    private javax.swing.JMenuItem jmiCadastrarFuncionarios;
    private javax.swing.JMenuItem jmiCadastrarMarca;
    private javax.swing.JMenuItem jmiCadastrarProdutos;
    private javax.swing.JMenuItem jmiNovaVenda;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
